name: WelcomeWarpSigns
main: com.wasteofplastic.wwarps.WWarps
version: 1.5 # Updated version
api-version: 1.13 # Added to ensure compatibility with modern Bukkit
description: Easy to use warp signs for players
author: tastybento
commands:
  wwarp:
    description: Warp to a player's sign or list available warps.
    usage: /<command> [player]
    permission: welcomewarpsigns.use
  wwarps:
    description: Open the warp panel or list warps.
    usage: /<command> [page]
    permission: welcomewarpsigns.use
  wwadmin:
    description: Admin commands for managing WWarps.
    usage: /<command> [reload|list|remove <player>]
    permission: welcomewarpsigns.admin

permissions:
  welcomewarpsigns.use:
    description: Allows players to use warp commands.
    default: true
  welcomewarpsigns.add:
    description: Allows players to create warp signs.
    default: op
  welcomewarpsigns.admin:
    description: Grants access to all admin commands.
    default: op
    children:
      welcomewarpsigns.admin.reload:
        description: Allows reloading the plugin configuration.
        default: op
      welcomewarpsigns.admin.list:
        description: Allows listing all active warps.
        default: op
      welcomewarpsigns.admin.remove:
        description: Allows removing a player's warp.
        default: op
