name: WelcomeWarpSigns
main: com.djtmk.wwarps.WWarps
version: 1.6
api-version: 1.21
description: Easy to use warp signs for players
author: tastybento
commands:
  wwarps:
    description: Opens the warp GUI or lists warps.
    usage: /<command> [list]
    permission: welcomewarpsigns.use
  wwarp:
    description: Warps to a player's warp.
    usage: /<command> <player>
    permission: welcomewarpsigns.use
  wwadmin:
    description: Admin commands for managing WWarps.
    usage: /<command> [reload|list|remove <player>]
    permission: welcomewarpsigns.admin
permissions:
  welcomewarpsigns.use:
    description: Allows players to use warp commands and GUI.
    default: true
  welcomewarpsigns.add:
    description: Allows players to create warp signs.
    default: true
  welcomewarpsigns.admin:
    description: Grants access to all admin commands.
    default: op
    children:
      welcomewarpsigns.admin.reload:
        description: Allows reloading the plugin configuration.
        default: op
      welcomewarpsigns.admin.list:
        description: Allows listing all active warps.
        default: op
      welcomewarpsigns.admin.remove:
        description: Allows removing a player's warp.
        default: op